<?php
//常量定义
//站点域名

define('BASE_PATH',dirname(__FILE__).'\..\..');

define('SITE_URL','http://www.mianshi8.com/');
//前台css路径
define('CSS_PATH','/assets/default/css/');
//前台js路径
define('JS_PATH','/assets/default/js/');
//前台img路径
define('IMAGES_PATH','/assets/default/images/');
//前台用户图片
define('IMAGES_USER_PHOTO','/upload/user_photo/');
//前台小组图片
define('IMAGES_GROUP_PHOTO','/upload/group_photo/');
//文章图片
define('IMAGES_ARTICLE_PHOTO','/upload/article/');
//文章分类图片
define('IMAGES_FENLEI_PHOTO','/upload/fenlei/');
//工具图标
define('IMAGES_TOOLICON_PHOTO','images/toolIcon/');
//前台css路径
define('CSS_BOXCOL','/assets/boxcol_data/');
//前台js路径
define('JS_BOXCOL','/assets/boxcol_data/');
//前台css路径
define('CSS_GLOBAL','/assets/global/css/');
//前台js路径
define('JS_GLOBAL','/assets/global/js/');
//网页图片路径
define('IMGAGES_GLOBAL','/assets/global/images/');
//公司logo路径
define('COMPANY_LOGO','/upload/companylogo/');
//用户简历路径
define('JIANLI','/upload/jianli/');
?>